### PR TITLE
BaseTemplate::getFooterIcons was deprecated in MediaWiki 1.35

### PR DESCRIPTION
**Pull request by carlonluca**

### CODE REVIEW

**Comment by dolfinus** [comment]
Hi. Why did you close the PR?

**Comment by carlonluca** [comment]
Hello, this PR is open. I closed one before this because I accidentally added two unrelated commits.

**Comment by carlonluca** [comment]
The reason why I sent this request can be seen here (black warning in the footer): https://github.com/dolfinus/DarkVector/pull/23#issuecomment-886593823.

**Comment by dolfinus** [comment]
Thank you!

**Pull request merged**
